--- 
default: 
  adapter: postgresql
  encoding: utf8
  host: localhost
  password: Ojukwu787
  pool: 5
  
  username: Updater
development: 
  adapter: postgresql
  database: dproject_development
  encoding: utf8
  host: localhost
  password: Ojukwu787
  pool: 5
  
  username: Updater
production: 
  adapter: posgresql
  database: dproject_production
  encoding: utf8
  password: Ojukwu787
  username: Updater
  host: localhost
test: 
  adapter: postgresql
  database: dproject_test
  encoding: utf8
  host: localhost
  password: Ojukwu787
  pool: 5
 
  username: Updater
